/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConfirmedServiceResponse_H_
#define	_ConfirmedServiceResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GetNameListResponse.h"
#include "ReadResponse.h"
#include "WriteResponse.h"
#include "GetVariableAccessAttributesResponse.h"
#include "DefineNamedVariableListResponse.h"
#include "GetNamedVariableListAttributesResponse.h"
#include "DeleteNamedVariableListResponse.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfirmedServiceResponse_PR {
	ConfirmedServiceResponse_PR_NOTHING,	/* No components present */
	ConfirmedServiceResponse_PR_getNameList,
	ConfirmedServiceResponse_PR_read,
	ConfirmedServiceResponse_PR_write,
	ConfirmedServiceResponse_PR_getVariableAccessAttributes,
	ConfirmedServiceResponse_PR_defineNamedVariableList,
	ConfirmedServiceResponse_PR_getNamedVariableListAttributes,
	ConfirmedServiceResponse_PR_deleteNamedVariableList
} ConfirmedServiceResponse_PR;

/* ConfirmedServiceResponse */
typedef struct ConfirmedServiceResponse {
	ConfirmedServiceResponse_PR present;
	union ConfirmedServiceResponse_u {
		GetNameListResponse_t	 getNameList;
		ReadResponse_t	 read;
		WriteResponse_t	 write;
		GetVariableAccessAttributesResponse_t	 getVariableAccessAttributes;
		DefineNamedVariableListResponse_t	 defineNamedVariableList;
		GetNamedVariableListAttributesResponse_t	 getNamedVariableListAttributes;
		DeleteNamedVariableListResponse_t	 deleteNamedVariableList;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmedServiceResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmedServiceResponse;
extern asn_CHOICE_specifics_t asn_SPC_ConfirmedServiceResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfirmedServiceResponse_1[7];
extern asn_per_constraints_t asn_PER_type_ConfirmedServiceResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmedServiceResponse_H_ */
#include "asn_internal.h"
