/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConfirmedRequestPdu_H_
#define	_ConfirmedRequestPdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Unsigned32.h"
#include "ConfirmedServiceRequest.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ConfirmedRequestPdu */
typedef struct ConfirmedRequestPdu {
	Unsigned32_t	 invokeID;
	ConfirmedServiceRequest_t	 confirmedServiceRequest;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmedRequestPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmedRequestPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_ConfirmedRequestPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfirmedRequestPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmedRequestPdu_H_ */
#include "asn_internal.h"
