/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DataSequence_H_
#define	_DataSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data;

/* DataSequence */
typedef struct DataSequence {
	A_SEQUENCE_OF(struct Data) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataSequence;
extern asn_SET_OF_specifics_t asn_SPC_DataSequence_specs_1;
extern asn_TYPE_member_t asn_MBR_DataSequence_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _DataSequence_H_ */
#include "asn_internal.h"
