/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DeleteNamedVariableListRequest_H_
#define	_DeleteNamedVariableListRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "Identifier.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeleteNamedVariableListRequest__scopeOfDelete {
	DeleteNamedVariableListRequest__scopeOfDelete_specific	= 0,
	DeleteNamedVariableListRequest__scopeOfDelete_aa_specific	= 1,
	DeleteNamedVariableListRequest__scopeOfDelete_domain	= 2,
	DeleteNamedVariableListRequest__scopeOfDelete_vmd	= 3
} e_DeleteNamedVariableListRequest__scopeOfDelete;

/* Forward declarations */
struct ObjectName;

/* DeleteNamedVariableListRequest */
typedef struct DeleteNamedVariableListRequest {
	long	 scopeOfDelete	/* DEFAULT 0 */;
	struct DeleteNamedVariableListRequest__listOfVariableListName {
		A_SEQUENCE_OF(struct ObjectName) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfVariableListName;
	Identifier_t	*domainName	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeleteNamedVariableListRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeleteNamedVariableListRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_DeleteNamedVariableListRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_DeleteNamedVariableListRequest_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _DeleteNamedVariableListRequest_H_ */
#include "asn_internal.h"
