/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetNamedVariableListAttributesResponse_H_
#define	_GetNamedVariableListAttributesResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableDef;

/* GetNamedVariableListAttributesResponse */
typedef struct GetNamedVariableListAttributesResponse {
	BOOLEAN_t	 mmsDeletable;
	struct GetNamedVariableListAttributesResponse__listOfVariable {
		A_SEQUENCE_OF(struct VariableDef) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetNamedVariableListAttributesResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetNamedVariableListAttributesResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_GetNamedVariableListAttributesResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_GetNamedVariableListAttributesResponse_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableDef.h"

#endif	/* _GetNamedVariableListAttributesResponse_H_ */
#include "asn_internal.h"
