/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_InitiateErrorPdu_H_
#define	_InitiateErrorPdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ServiceError.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateErrorPdu */
typedef ServiceError_t	 InitiateErrorPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateErrorPdu;
asn_struct_free_f InitiateErrorPdu_free;
asn_struct_print_f InitiateErrorPdu_print;
asn_constr_check_f InitiateErrorPdu_constraint;
ber_type_decoder_f InitiateErrorPdu_decode_ber;
der_type_encoder_f InitiateErrorPdu_encode_der;
xer_type_decoder_f InitiateErrorPdu_decode_xer;
xer_type_encoder_f InitiateErrorPdu_encode_xer;
oer_type_decoder_f InitiateErrorPdu_decode_oer;
oer_type_encoder_f InitiateErrorPdu_encode_oer;
per_type_decoder_f InitiateErrorPdu_decode_uper;
per_type_encoder_f InitiateErrorPdu_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateErrorPdu_H_ */
#include "asn_internal.h"
