/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_UnconfirmedPDU_H_
#define	_UnconfirmedPDU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UnconfirmedService.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UnconfirmedPDU */
typedef struct UnconfirmedPDU {
	UnconfirmedService_t	 unconfirmedService;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnconfirmedPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnconfirmedPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_UnconfirmedPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_UnconfirmedPDU_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UnconfirmedPDU_H_ */
#include "asn_internal.h"
