/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Unsigned8_H_
#define	_Unsigned8_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Unsigned8 */
typedef long	 Unsigned8_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Unsigned8_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Unsigned8;
asn_struct_free_f Unsigned8_free;
asn_struct_print_f Unsigned8_print;
asn_constr_check_f Unsigned8_constraint;
ber_type_decoder_f Unsigned8_decode_ber;
der_type_encoder_f Unsigned8_encode_der;
xer_type_decoder_f Unsigned8_decode_xer;
xer_type_encoder_f Unsigned8_encode_xer;
oer_type_decoder_f Unsigned8_decode_oer;
oer_type_encoder_f Unsigned8_encode_oer;
per_type_decoder_f Unsigned8_decode_uper;
per_type_encoder_f Unsigned8_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Unsigned8_H_ */
#include "asn_internal.h"
