/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_UtcTime_H_
#define	_UtcTime_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTime */
typedef OCTET_STRING_t	 UtcTime_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UtcTime_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UtcTime;
asn_struct_free_f UtcTime_free;
asn_struct_print_f UtcTime_print;
asn_constr_check_f UtcTime_constraint;
ber_type_decoder_f UtcTime_decode_ber;
der_type_encoder_f UtcTime_encode_der;
xer_type_decoder_f UtcTime_decode_xer;
xer_type_encoder_f UtcTime_encode_xer;
oer_type_decoder_f UtcTime_decode_oer;
oer_type_encoder_f UtcTime_encode_oer;
per_type_decoder_f UtcTime_decode_uper;
per_type_encoder_f UtcTime_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTime_H_ */
#include "asn_internal.h"
