/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VariableAccessSpecification_H_
#define	_VariableAccessSpecification_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VariableAccessSpecification_PR {
	VariableAccessSpecification_PR_NOTHING,	/* No components present */
	VariableAccessSpecification_PR_listOfVariable,
	VariableAccessSpecification_PR_variableListName
} VariableAccessSpecification_PR;

/* Forward declarations */
struct VariableDef;

/* VariableAccessSpecification */
typedef struct VariableAccessSpecification {
	VariableAccessSpecification_PR present;
	union VariableAccessSpecification_u {
		struct VariableAccessSpecification__listOfVariable {
			A_SEQUENCE_OF(struct VariableDef) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} listOfVariable;
		ObjectName_t	 variableListName;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VariableAccessSpecification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VariableAccessSpecification;
extern asn_CHOICE_specifics_t asn_SPC_VariableAccessSpecification_specs_1;
extern asn_TYPE_member_t asn_MBR_VariableAccessSpecification_1[2];
extern asn_per_constraints_t asn_PER_type_VariableAccessSpecification_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableDef.h"

#endif	/* _VariableAccessSpecification_H_ */
#include "asn_internal.h"
