/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Calling_presentation_selector_H_
#define	_Calling_presentation_selector_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Presentation-selector.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Calling-presentation-selector */
typedef Presentation_selector_t	 Calling_presentation_selector_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Calling_presentation_selector_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Calling_presentation_selector;
asn_struct_free_f Calling_presentation_selector_free;
asn_struct_print_f Calling_presentation_selector_print;
asn_constr_check_f Calling_presentation_selector_constraint;
ber_type_decoder_f Calling_presentation_selector_decode_ber;
der_type_encoder_f Calling_presentation_selector_encode_der;
xer_type_decoder_f Calling_presentation_selector_decode_xer;
xer_type_encoder_f Calling_presentation_selector_encode_xer;
oer_type_decoder_f Calling_presentation_selector_decode_oer;
oer_type_encoder_f Calling_presentation_selector_encode_oer;
per_type_decoder_f Calling_presentation_selector_decode_uper;
per_type_encoder_f Calling_presentation_selector_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Calling_presentation_selector_H_ */
#include <asn_internal.h>
