/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Protocol_options_H_
#define	_Protocol_options_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Protocol_options {
	Protocol_options_nominated_context	= 0,
	Protocol_options_short_encoding	= 1,
	Protocol_options_packed_encoding_rules	= 2
} e_Protocol_options;

/* Protocol-options */
typedef BIT_STRING_t	 Protocol_options_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Protocol_options;
asn_struct_free_f Protocol_options_free;
asn_struct_print_f Protocol_options_print;
asn_constr_check_f Protocol_options_constraint;
ber_type_decoder_f Protocol_options_decode_ber;
der_type_encoder_f Protocol_options_encode_der;
xer_type_decoder_f Protocol_options_decode_xer;
xer_type_encoder_f Protocol_options_encode_xer;
oer_type_decoder_f Protocol_options_decode_oer;
oer_type_encoder_f Protocol_options_encode_oer;
per_type_decoder_f Protocol_options_decode_uper;
per_type_encoder_f Protocol_options_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Protocol_options_H_ */
#include <asn_internal.h>
