/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Simply_encoded_data_H_
#define	_Simply_encoded_data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Simply-encoded-data */
typedef OCTET_STRING_t	 Simply_encoded_data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Simply_encoded_data;
asn_struct_free_f Simply_encoded_data_free;
asn_struct_print_f Simply_encoded_data_print;
asn_constr_check_f Simply_encoded_data_constraint;
ber_type_decoder_f Simply_encoded_data_decode_ber;
der_type_encoder_f Simply_encoded_data_encode_der;
xer_type_decoder_f Simply_encoded_data_decode_xer;
xer_type_encoder_f Simply_encoded_data_encode_xer;
oer_type_decoder_f Simply_encoded_data_decode_oer;
oer_type_encoder_f Simply_encoded_data_encode_oer;
per_type_decoder_f Simply_encoded_data_decode_uper;
per_type_encoder_f Simply_encoded_data_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Simply_encoded_data_H_ */
#include <asn_internal.h>
