/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AlternateAccessSelection.h"

static asn_oer_constraints_t asn_OER_type_AlternateAccessSelection_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AlternateAccessSelection_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_indexRange_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__indexRange, lowIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lowIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess__indexRange, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberOfElements"
		},
};
static const ber_tlv_tag_t asn_DEF_indexRange_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_indexRange_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowIndex */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* numberOfElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_indexRange_specs_5 = {
	sizeof(struct AlternateAccessSelection__selectAlternateAccess__indexRange),
	offsetof(struct AlternateAccessSelection__selectAlternateAccess__indexRange, _asn_ctx),
	asn_MAP_indexRange_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_indexRange_5 = {
	"indexRange",
	"indexRange",
	&asn_OP_SEQUENCE,
	asn_DEF_indexRange_tags_5,
	sizeof(asn_DEF_indexRange_tags_5)
		/sizeof(asn_DEF_indexRange_tags_5[0]) - 1, /* 1 */
	asn_DEF_indexRange_tags_5,	/* Same as above */
	sizeof(asn_DEF_indexRange_tags_5)
		/sizeof(asn_DEF_indexRange_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_indexRange_5,
	2,	/* Elements count */
	&asn_SPC_indexRange_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectAlternateAccess_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, component),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, index),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, indexRange),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_indexRange_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, allElements),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allElements"
		},
	{ ATF_POINTER, 0, offsetof(struct AlternateAccessSelection__selectAlternateAccess, alternateAccess),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlternateAccess,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alternateAccess"
		},
};
static const ber_tlv_tag_t asn_DEF_selectAlternateAccess_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_selectAlternateAccess_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, 0, 0 }, /* alternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* allElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_selectAlternateAccess_specs_2 = {
	sizeof(struct AlternateAccessSelection__selectAlternateAccess),
	offsetof(struct AlternateAccessSelection__selectAlternateAccess, _asn_ctx),
	asn_MAP_selectAlternateAccess_tag2el_2,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectAlternateAccess_2 = {
	"selectAlternateAccess",
	"selectAlternateAccess",
	&asn_OP_SEQUENCE,
	asn_DEF_selectAlternateAccess_tags_2,
	sizeof(asn_DEF_selectAlternateAccess_tags_2)
		/sizeof(asn_DEF_selectAlternateAccess_tags_2[0]) - 1, /* 1 */
	asn_DEF_selectAlternateAccess_tags_2,	/* Same as above */
	sizeof(asn_DEF_selectAlternateAccess_tags_2)
		/sizeof(asn_DEF_selectAlternateAccess_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_selectAlternateAccess_2,
	5,	/* Elements count */
	&asn_SPC_selectAlternateAccess_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AlternateAccessSelection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.selectAlternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_selectAlternateAccess_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"selectAlternateAccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IndexRangeSeq,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccessSelection, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allElements"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AlternateAccessSelection_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* selectAlternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* allElements */
};
asn_CHOICE_specifics_t asn_SPC_AlternateAccessSelection_specs_1 = {
	sizeof(struct AlternateAccessSelection),
	offsetof(struct AlternateAccessSelection, _asn_ctx),
	offsetof(struct AlternateAccessSelection, present),
	sizeof(((struct AlternateAccessSelection *)0)->present),
	asn_MAP_AlternateAccessSelection_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AlternateAccessSelection = {
	"AlternateAccessSelection",
	"AlternateAccessSelection",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AlternateAccessSelection_constr_1, &asn_PER_type_AlternateAccessSelection_constr_1, CHOICE_constraint },
	asn_MBR_AlternateAccessSelection_1,
	5,	/* Elements count */
	&asn_SPC_AlternateAccessSelection_specs_1	/* Additional specs */
};

