/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ConfirmedResponsePdu.h"

asn_TYPE_member_t asn_MBR_ConfirmedResponsePdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedResponsePdu, invokeID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"invokeID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedResponsePdu, confirmedServiceResponse),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ConfirmedServiceResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmedServiceResponse"
		},
};
static const ber_tlv_tag_t asn_DEF_ConfirmedResponsePdu_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConfirmedResponsePdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* invokeID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* getNameList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* read */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* write */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 }, /* getVariableAccessAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 1, 0, 0 }, /* defineNamedVariableList */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 0 }, /* getNamedVariableListAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 1, 0, 0 } /* deleteNamedVariableList */
};
asn_SEQUENCE_specifics_t asn_SPC_ConfirmedResponsePdu_specs_1 = {
	sizeof(struct ConfirmedResponsePdu),
	offsetof(struct ConfirmedResponsePdu, _asn_ctx),
	asn_MAP_ConfirmedResponsePdu_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConfirmedResponsePdu = {
	"ConfirmedResponsePdu",
	"ConfirmedResponsePdu",
	&asn_OP_SEQUENCE,
	asn_DEF_ConfirmedResponsePdu_tags_1,
	sizeof(asn_DEF_ConfirmedResponsePdu_tags_1)
		/sizeof(asn_DEF_ConfirmedResponsePdu_tags_1[0]), /* 1 */
	asn_DEF_ConfirmedResponsePdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConfirmedResponsePdu_tags_1)
		/sizeof(asn_DEF_ConfirmedResponsePdu_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConfirmedResponsePdu_1,
	2,	/* Elements count */
	&asn_SPC_ConfirmedResponsePdu_specs_1	/* Additional specs */
};

