/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "DeleteNamedVariableListRequest.h"

static int asn_DFL_2_cmp_0(const void *sptr) {
	const long *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
static asn_TYPE_member_t asn_MBR_listOfVariableListName_7[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfVariableListName_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfVariableListName_specs_7 = {
	sizeof(struct DeleteNamedVariableListRequest__listOfVariableListName),
	offsetof(struct DeleteNamedVariableListRequest__listOfVariableListName, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfVariableListName_7 = {
	"listOfVariableListName",
	"listOfVariableListName",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfVariableListName_tags_7,
	sizeof(asn_DEF_listOfVariableListName_tags_7)
		/sizeof(asn_DEF_listOfVariableListName_tags_7[0]) - 1, /* 1 */
	asn_DEF_listOfVariableListName_tags_7,	/* Same as above */
	sizeof(asn_DEF_listOfVariableListName_tags_7)
		/sizeof(asn_DEF_listOfVariableListName_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_listOfVariableListName_7,
	1,	/* Single element */
	&asn_SPC_listOfVariableListName_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DeleteNamedVariableListRequest_1[] = {
	{ ATF_NOFLAGS, 3, offsetof(struct DeleteNamedVariableListRequest, scopeOfDelete),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"scopeOfDelete"
		},
	{ ATF_POINTER, 2, offsetof(struct DeleteNamedVariableListRequest, listOfVariableListName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfVariableListName_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfVariableListName"
		},
	{ ATF_POINTER, 1, offsetof(struct DeleteNamedVariableListRequest, domainName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"domainName"
		},
};
static const int asn_MAP_DeleteNamedVariableListRequest_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_DeleteNamedVariableListRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DeleteNamedVariableListRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scopeOfDelete */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfVariableListName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* domainName */
};
asn_SEQUENCE_specifics_t asn_SPC_DeleteNamedVariableListRequest_specs_1 = {
	sizeof(struct DeleteNamedVariableListRequest),
	offsetof(struct DeleteNamedVariableListRequest, _asn_ctx),
	asn_MAP_DeleteNamedVariableListRequest_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_DeleteNamedVariableListRequest_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DeleteNamedVariableListRequest = {
	"DeleteNamedVariableListRequest",
	"DeleteNamedVariableListRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_DeleteNamedVariableListRequest_tags_1,
	sizeof(asn_DEF_DeleteNamedVariableListRequest_tags_1)
		/sizeof(asn_DEF_DeleteNamedVariableListRequest_tags_1[0]), /* 1 */
	asn_DEF_DeleteNamedVariableListRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_DeleteNamedVariableListRequest_tags_1)
		/sizeof(asn_DEF_DeleteNamedVariableListRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DeleteNamedVariableListRequest_1,
	3,	/* Elements count */
	&asn_SPC_DeleteNamedVariableListRequest_specs_1	/* Additional specs */
};

