/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetNameListResponse.h"

static asn_TYPE_member_t asn_MBR_listOfIdentifier_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfIdentifier_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfIdentifier_specs_2 = {
	sizeof(struct GetNameListResponse__listOfIdentifier),
	offsetof(struct GetNameListResponse__listOfIdentifier, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfIdentifier_2 = {
	"listOfIdentifier",
	"listOfIdentifier",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfIdentifier_tags_2,
	sizeof(asn_DEF_listOfIdentifier_tags_2)
		/sizeof(asn_DEF_listOfIdentifier_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfIdentifier_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfIdentifier_tags_2)
		/sizeof(asn_DEF_listOfIdentifier_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_listOfIdentifier_2,
	1,	/* Single element */
	&asn_SPC_listOfIdentifier_specs_2	/* Additional specs */
};

static int asn_DFL_4_cmp_1(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 1 */
	return (*st != 1);
}
static int asn_DFL_4_set_1(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 1 */
	*st = 1;
	return 0;
}
asn_TYPE_member_t asn_MBR_GetNameListResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameListResponse, listOfIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_listOfIdentifier_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfIdentifier"
		},
	{ ATF_POINTER, 1, offsetof(struct GetNameListResponse, moreFollows),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		&asn_DFL_4_cmp_1,	/* Compare DEFAULT 1 */
		&asn_DFL_4_set_1,	/* Set DEFAULT 1 */
		"moreFollows"
		},
};
static const int asn_MAP_GetNameListResponse_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_GetNameListResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetNameListResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* moreFollows */
};
asn_SEQUENCE_specifics_t asn_SPC_GetNameListResponse_specs_1 = {
	sizeof(struct GetNameListResponse),
	offsetof(struct GetNameListResponse, _asn_ctx),
	asn_MAP_GetNameListResponse_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_GetNameListResponse_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetNameListResponse = {
	"GetNameListResponse",
	"GetNameListResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_GetNameListResponse_tags_1,
	sizeof(asn_DEF_GetNameListResponse_tags_1)
		/sizeof(asn_DEF_GetNameListResponse_tags_1[0]), /* 1 */
	asn_DEF_GetNameListResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetNameListResponse_tags_1)
		/sizeof(asn_DEF_GetNameListResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GetNameListResponse_1,
	2,	/* Elements count */
	&asn_SPC_GetNameListResponse_specs_1	/* Additional specs */
};

