/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetVariableAccessAttributesResponse.h"

asn_TYPE_member_t asn_MBR_GetVariableAccessAttributesResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetVariableAccessAttributesResponse, mmsDeletable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mmsDeletable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetVariableAccessAttributesResponse, typeSpecification),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeSpecification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"typeSpecification"
		},
};
static const ber_tlv_tag_t asn_DEF_GetVariableAccessAttributesResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetVariableAccessAttributesResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mmsDeletable */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* typeSpecification */
};
asn_SEQUENCE_specifics_t asn_SPC_GetVariableAccessAttributesResponse_specs_1 = {
	sizeof(struct GetVariableAccessAttributesResponse),
	offsetof(struct GetVariableAccessAttributesResponse, _asn_ctx),
	asn_MAP_GetVariableAccessAttributesResponse_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributesResponse = {
	"GetVariableAccessAttributesResponse",
	"GetVariableAccessAttributesResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_GetVariableAccessAttributesResponse_tags_1,
	sizeof(asn_DEF_GetVariableAccessAttributesResponse_tags_1)
		/sizeof(asn_DEF_GetVariableAccessAttributesResponse_tags_1[0]), /* 1 */
	asn_DEF_GetVariableAccessAttributesResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetVariableAccessAttributesResponse_tags_1)
		/sizeof(asn_DEF_GetVariableAccessAttributesResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GetVariableAccessAttributesResponse_1,
	2,	/* Elements count */
	&asn_SPC_GetVariableAccessAttributesResponse_specs_1	/* Additional specs */
};

