/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "InitiateRequestPdu.h"

asn_TYPE_member_t asn_MBR_InitiateRequestPdu_1[] = {
	{ ATF_POINTER, 1, offsetof(struct InitiateRequestPdu, localDetailCalling),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"localDetailCalling"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateRequestPdu, proposedMaxServOutstandingCalling),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"proposedMaxServOutstandingCalling"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateRequestPdu, proposedMaxServOutstandingCalled),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"proposedMaxServOutstandingCalled"
		},
	{ ATF_POINTER, 1, offsetof(struct InitiateRequestPdu, proposedDataStructureNestingLevel),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"proposedDataStructureNestingLevel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateRequestPdu, mmsInitRequestDetail),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitRequestDetail,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mmsInitRequestDetail"
		},
};
static const int asn_MAP_InitiateRequestPdu_oms_1[] = { 0, 3 };
static const ber_tlv_tag_t asn_DEF_InitiateRequestPdu_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitiateRequestPdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* localDetailCalling */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* proposedMaxServOutstandingCalling */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* proposedMaxServOutstandingCalled */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* proposedDataStructureNestingLevel */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* mmsInitRequestDetail */
};
asn_SEQUENCE_specifics_t asn_SPC_InitiateRequestPdu_specs_1 = {
	sizeof(struct InitiateRequestPdu),
	offsetof(struct InitiateRequestPdu, _asn_ctx),
	asn_MAP_InitiateRequestPdu_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_InitiateRequestPdu_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitiateRequestPdu = {
	"InitiateRequestPdu",
	"InitiateRequestPdu",
	&asn_OP_SEQUENCE,
	asn_DEF_InitiateRequestPdu_tags_1,
	sizeof(asn_DEF_InitiateRequestPdu_tags_1)
		/sizeof(asn_DEF_InitiateRequestPdu_tags_1[0]), /* 1 */
	asn_DEF_InitiateRequestPdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiateRequestPdu_tags_1)
		/sizeof(asn_DEF_InitiateRequestPdu_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitiateRequestPdu_1,
	5,	/* Elements count */
	&asn_SPC_InitiateRequestPdu_specs_1	/* Additional specs */
};

