/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "MmsPdu.h"

static asn_oer_constraints_t asn_OER_type_MmsPdu_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_MmsPdu_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_MmsPdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MmsPdu, choice.confirmedRequestPdu),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConfirmedRequestPdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmedRequestPdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MmsPdu, choice.confirmedResponsePdu),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConfirmedResponsePdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmedResponsePdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MmsPdu, choice.unconfirmedPDU),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UnconfirmedPDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unconfirmedPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MmsPdu, choice.initiateRequestPdu),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateRequestPdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateRequestPdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MmsPdu, choice.initiateResponsePdu),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateResponsePdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateResponsePdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MmsPdu, choice.initiateErrorPdu),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateErrorPdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateErrorPdu"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MmsPdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* confirmedRequestPdu */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* confirmedResponsePdu */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* unconfirmedPDU */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 3, 0, 0 }, /* initiateRequestPdu */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 4, 0, 0 }, /* initiateResponsePdu */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 5, 0, 0 } /* initiateErrorPdu */
};
static asn_CHOICE_specifics_t asn_SPC_MmsPdu_specs_1 = {
	sizeof(struct MmsPdu),
	offsetof(struct MmsPdu, _asn_ctx),
	offsetof(struct MmsPdu, present),
	sizeof(((struct MmsPdu *)0)->present),
	asn_MAP_MmsPdu_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MmsPdu = {
	"MmsPdu",
	"MmsPdu",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_MmsPdu_constr_1, &asn_PER_type_MmsPdu_constr_1, CHOICE_constraint },
	asn_MBR_MmsPdu_1,
	6,	/* Elements count */
	&asn_SPC_MmsPdu_specs_1	/* Additional specs */
};

