/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ServiceError.h"

static asn_oer_constraints_t asn_OER_type_errorClass_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_errorClass_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  12 }	/* (0..12) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_errorClass_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.vmd_state),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vmd-state"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.application_reference),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"application-reference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.definition),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"definition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.resource),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resource"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.service),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"service"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.service_preempt),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"service-preempt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.time_resolution),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"time-resolution"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.access),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"access"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.initiate),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.conclude),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"conclude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.cancel),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.file),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"file"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError__errorClass, choice.others),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"others"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_errorClass_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vmd-state */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* application-reference */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* definition */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* resource */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* service */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* service-preempt */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* time-resolution */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* access */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* initiate */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* conclude */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* cancel */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* file */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 } /* others */
};
static asn_CHOICE_specifics_t asn_SPC_errorClass_specs_2 = {
	sizeof(struct ServiceError__errorClass),
	offsetof(struct ServiceError__errorClass, _asn_ctx),
	offsetof(struct ServiceError__errorClass, present),
	sizeof(((struct ServiceError__errorClass *)0)->present),
	asn_MAP_errorClass_tag2el_2,
	13,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_errorClass_2 = {
	"errorClass",
	"errorClass",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_errorClass_constr_2, &asn_PER_type_errorClass_constr_2, CHOICE_constraint },
	asn_MBR_errorClass_2,
	13,	/* Elements count */
	&asn_SPC_errorClass_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ServiceError_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceError, errorClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_errorClass_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"errorClass"
		},
	{ ATF_POINTER, 2, offsetof(struct ServiceError, additionalCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalCode"
		},
	{ ATF_POINTER, 1, offsetof(struct ServiceError, additionalDescription),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalDescription"
		},
};
static const int asn_MAP_ServiceError_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_ServiceError_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ServiceError_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* errorClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* additionalCode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* additionalDescription */
};
asn_SEQUENCE_specifics_t asn_SPC_ServiceError_specs_1 = {
	sizeof(struct ServiceError),
	offsetof(struct ServiceError, _asn_ctx),
	asn_MAP_ServiceError_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ServiceError_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ServiceError = {
	"ServiceError",
	"ServiceError",
	&asn_OP_SEQUENCE,
	asn_DEF_ServiceError_tags_1,
	sizeof(asn_DEF_ServiceError_tags_1)
		/sizeof(asn_DEF_ServiceError_tags_1[0]), /* 1 */
	asn_DEF_ServiceError_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceError_tags_1)
		/sizeof(asn_DEF_ServiceError_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ServiceError_1,
	3,	/* Elements count */
	&asn_SPC_ServiceError_specs_1	/* Additional specs */
};

