/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "UnconfirmedService.h"

static asn_oer_constraints_t asn_OER_type_UnconfirmedService_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_UnconfirmedService_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_UnconfirmedService_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UnconfirmedService, choice.informationReport),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InformationReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"informationReport"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UnconfirmedService_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* informationReport */
};
asn_CHOICE_specifics_t asn_SPC_UnconfirmedService_specs_1 = {
	sizeof(struct UnconfirmedService),
	offsetof(struct UnconfirmedService, _asn_ctx),
	offsetof(struct UnconfirmedService, present),
	sizeof(((struct UnconfirmedService *)0)->present),
	asn_MAP_UnconfirmedService_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UnconfirmedService = {
	"UnconfirmedService",
	"UnconfirmedService",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_UnconfirmedService_constr_1, &asn_PER_type_UnconfirmedService_constr_1, CHOICE_constraint },
	asn_MBR_UnconfirmedService_1,
	1,	/* Elements count */
	&asn_SPC_UnconfirmedService_specs_1	/* Additional specs */
};

