/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "UnconfirmedPDU.h"

asn_TYPE_member_t asn_MBR_UnconfirmedPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UnconfirmedPDU, unconfirmedService),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_UnconfirmedService,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unconfirmedService"
		},
};
static const ber_tlv_tag_t asn_DEF_UnconfirmedPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UnconfirmedPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* informationReport */
};
asn_SEQUENCE_specifics_t asn_SPC_UnconfirmedPDU_specs_1 = {
	sizeof(struct UnconfirmedPDU),
	offsetof(struct UnconfirmedPDU, _asn_ctx),
	asn_MAP_UnconfirmedPDU_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UnconfirmedPDU = {
	"UnconfirmedPDU",
	"UnconfirmedPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_UnconfirmedPDU_tags_1,
	sizeof(asn_DEF_UnconfirmedPDU_tags_1)
		/sizeof(asn_DEF_UnconfirmedPDU_tags_1[0]), /* 1 */
	asn_DEF_UnconfirmedPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_UnconfirmedPDU_tags_1)
		/sizeof(asn_DEF_UnconfirmedPDU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UnconfirmedPDU_1,
	1,	/* Elements count */
	&asn_SPC_UnconfirmedPDU_specs_1	/* Additional specs */
};

