/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "Default-context-name.h"

asn_TYPE_member_t asn_MBR_Default_context_name_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Default_context_name, abstract_syntax_name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Abstract_syntax_name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"abstract-syntax-name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Default_context_name, transfer_syntax_name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Transfer_syntax_name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transfer-syntax-name"
		},
};
static const ber_tlv_tag_t asn_DEF_Default_context_name_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Default_context_name_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* abstract-syntax-name */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* transfer-syntax-name */
};
asn_SEQUENCE_specifics_t asn_SPC_Default_context_name_specs_1 = {
	sizeof(struct Default_context_name),
	offsetof(struct Default_context_name, _asn_ctx),
	asn_MAP_Default_context_name_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Default_context_name = {
	"Default-context-name",
	"Default-context-name",
	&asn_OP_SEQUENCE,
	asn_DEF_Default_context_name_tags_1,
	sizeof(asn_DEF_Default_context_name_tags_1)
		/sizeof(asn_DEF_Default_context_name_tags_1[0]), /* 1 */
	asn_DEF_Default_context_name_tags_1,	/* Same as above */
	sizeof(asn_DEF_Default_context_name_tags_1)
		/sizeof(asn_DEF_Default_context_name_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Default_context_name_1,
	2,	/* Elements count */
	&asn_SPC_Default_context_name_specs_1	/* Additional specs */
};

