/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "User-data.h"

static asn_oer_constraints_t asn_OER_type_User_data_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_User_data_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_User_data_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct User_data, choice.simply_encoded_data),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Simply_encoded_data,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simply-encoded-data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct User_data, choice.fully_encoded_data),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Fully_encoded_data,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fully-encoded-data"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_User_data_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* simply-encoded-data */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 } /* fully-encoded-data */
};
asn_CHOICE_specifics_t asn_SPC_User_data_specs_1 = {
	sizeof(struct User_data),
	offsetof(struct User_data, _asn_ctx),
	offsetof(struct User_data, present),
	sizeof(((struct User_data *)0)->present),
	asn_MAP_User_data_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_User_data = {
	"User-data",
	"User-data",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_User_data_constr_1, &asn_PER_type_User_data_constr_1, CHOICE_constraint },
	asn_MBR_User_data_1,
	2,	/* Elements count */
	&asn_SPC_User_data_specs_1	/* Additional specs */
};

