/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "Mode-selector.h"

asn_TYPE_member_t asn_MBR_Mode_selector_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Mode_selector, mode_value),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mode-value"
		},
};
static const ber_tlv_tag_t asn_DEF_Mode_selector_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Mode_selector_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* mode-value */
};
static const uint8_t asn_MAP_Mode_selector_mmap_1[(1 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7)
};
asn_SET_specifics_t asn_SPC_Mode_selector_specs_1 = {
	sizeof(struct Mode_selector),
	offsetof(struct Mode_selector, _asn_ctx),
	offsetof(struct Mode_selector, _presence_map),
	asn_MAP_Mode_selector_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_Mode_selector_tag2el_1,	/* Same as above */
	1,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(const unsigned int *)asn_MAP_Mode_selector_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_Mode_selector = {
	"Mode-selector",
	"Mode-selector",
	&asn_OP_SET,
	asn_DEF_Mode_selector_tags_1,
	sizeof(asn_DEF_Mode_selector_tags_1)
		/sizeof(asn_DEF_Mode_selector_tags_1[0]), /* 1 */
	asn_DEF_Mode_selector_tags_1,	/* Same as above */
	sizeof(asn_DEF_Mode_selector_tags_1)
		/sizeof(asn_DEF_Mode_selector_tags_1[0]), /* 1 */
	{ 0, 0, SET_constraint },
	asn_MBR_Mode_selector_1,
	1,	/* Elements count */
	&asn_SPC_Mode_selector_specs_1	/* Additional specs */
};

