/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CP_type;
extern struct asn_TYPE_descriptor_s asn_DEF_CPC_type;
extern struct asn_TYPE_descriptor_s asn_DEF_CPA_PPDU;
extern struct asn_TYPE_descriptor_s asn_DEF_Abort_reason;
extern struct asn_TYPE_descriptor_s asn_DEF_Default_context_result;
extern struct asn_TYPE_descriptor_s asn_DEF_Event_identifier;
extern struct asn_TYPE_descriptor_s asn_DEF_Presentation_context_addition_list;
extern struct asn_TYPE_descriptor_s asn_DEF_Presentation_context_addition_result_list;
extern struct asn_TYPE_descriptor_s asn_DEF_Presentation_context_deletion_list;
extern struct asn_TYPE_descriptor_s asn_DEF_Presentation_context_deletion_result_list;
extern struct asn_TYPE_descriptor_s asn_DEF_Presentation_context_identifier_list;
extern struct asn_TYPE_descriptor_s asn_DEF_Provider_reason;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ISO8823-PRESENTATION in ISO8823_NEW.asn1 */
	&asn_DEF_CP_type,	
	&asn_DEF_CPC_type,	
	&asn_DEF_CPA_PPDU,	
	&asn_DEF_Abort_reason,	
	&asn_DEF_Default_context_result,	
	&asn_DEF_Event_identifier,	
	&asn_DEF_Presentation_context_addition_list,	
	&asn_DEF_Presentation_context_addition_result_list,	
	&asn_DEF_Presentation_context_deletion_list,	
	&asn_DEF_Presentation_context_deletion_result_list,	
	&asn_DEF_Presentation_context_identifier_list,	
	&asn_DEF_Provider_reason,	
	/* From module ASN1C-UsefulInformationObjectClasses in /usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

