/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "Presentation-context-definition-list.h"

int
Presentation_context_definition_list_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 7)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using Context_list,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Presentation_context_definition_list_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..7)) */};
asn_per_constraints_t asn_PER_type_Presentation_context_definition_list_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (SIZE(0..7)) */,
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_Presentation_context_definition_list_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Presentation_context_definition_list = {
	"Presentation-context-definition-list",
	"Presentation-context-definition-list",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Presentation_context_definition_list_tags_1,
	sizeof(asn_DEF_Presentation_context_definition_list_tags_1)
		/sizeof(asn_DEF_Presentation_context_definition_list_tags_1[0]), /* 1 */
	asn_DEF_Presentation_context_definition_list_tags_1,	/* Same as above */
	sizeof(asn_DEF_Presentation_context_definition_list_tags_1)
		/sizeof(asn_DEF_Presentation_context_definition_list_tags_1[0]), /* 1 */
	{ &asn_OER_type_Presentation_context_definition_list_constr_1, &asn_PER_type_Presentation_context_definition_list_constr_1, Presentation_context_definition_list_constraint },
	asn_MBR_Context_list_1,
	1,	/* Single element */
	&asn_SPC_Context_list_specs_1	/* Additional specs */
};

