/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "AARQ-apdu.h"

asn_TYPE_member_t asn_MBR_AARQ_apdu_1[] = {
	{ ATF_POINTER, 1, offsetof(struct AARQ_apdu, protocol_version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocol-version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AARQ_apdu, application_context_name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Application_context_name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"application-context-name"
		},
	{ ATF_POINTER, 14, offsetof(struct AARQ_apdu, called_AP_title),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AP_title,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"called-AP-title"
		},
	{ ATF_POINTER, 13, offsetof(struct AARQ_apdu, called_AE_qualifier),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AE_qualifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"called-AE-qualifier"
		},
	{ ATF_POINTER, 12, offsetof(struct AARQ_apdu, called_AP_invocation_identifier),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AP_invocation_identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"called-AP-invocation-identifier"
		},
	{ ATF_POINTER, 11, offsetof(struct AARQ_apdu, called_AE_invocation_identifier),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AE_invocation_identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"called-AE-invocation-identifier"
		},
	{ ATF_POINTER, 10, offsetof(struct AARQ_apdu, calling_AP_title),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AP_title,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"calling-AP-title"
		},
	{ ATF_POINTER, 9, offsetof(struct AARQ_apdu, calling_AE_qualifier),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AE_qualifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"calling-AE-qualifier"
		},
	{ ATF_POINTER, 8, offsetof(struct AARQ_apdu, calling_AP_invocation_identifier),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AP_invocation_identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"calling-AP-invocation-identifier"
		},
	{ ATF_POINTER, 7, offsetof(struct AARQ_apdu, calling_AE_invocation_identifier),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AE_invocation_identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"calling-AE-invocation-identifier"
		},
	{ ATF_POINTER, 6, offsetof(struct AARQ_apdu, sender_acse_requirements),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ACSE_requirements,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sender-acse-requirements"
		},
	{ ATF_POINTER, 5, offsetof(struct AARQ_apdu, mechanism_name),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Mechanism_name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mechanism-name"
		},
	{ ATF_POINTER, 4, offsetof(struct AARQ_apdu, calling_authentication_value),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Authentication_value,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"calling-authentication-value"
		},
	{ ATF_POINTER, 3, offsetof(struct AARQ_apdu, application_context_name_list),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Application_context_name_list,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"application-context-name-list"
		},
	{ ATF_POINTER, 2, offsetof(struct AARQ_apdu, implementation_information),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Implementation_data,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"implementation-information"
		},
	{ ATF_POINTER, 1, offsetof(struct AARQ_apdu, user_information),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Association_information,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"user-information"
		},
};
static const int asn_MAP_AARQ_apdu_oms_1[] = { 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
static const ber_tlv_tag_t asn_DEF_AARQ_apdu_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AARQ_apdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocol-version */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* application-context-name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* called-AP-title */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* called-AE-qualifier */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* called-AP-invocation-identifier */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* called-AE-invocation-identifier */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* calling-AP-title */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* calling-AE-qualifier */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* calling-AP-invocation-identifier */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* calling-AE-invocation-identifier */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* sender-acse-requirements */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* mechanism-name */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* calling-authentication-value */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* application-context-name-list */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 14, 0, 0 }, /* implementation-information */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 15, 0, 0 } /* user-information */
};
asn_SEQUENCE_specifics_t asn_SPC_AARQ_apdu_specs_1 = {
	sizeof(struct AARQ_apdu),
	offsetof(struct AARQ_apdu, _asn_ctx),
	asn_MAP_AARQ_apdu_tag2el_1,
	16,	/* Count of tags in the map */
	asn_MAP_AARQ_apdu_oms_1,	/* Optional members */
	15, 0,	/* Root/Additions */
	16,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AARQ_apdu = {
	"AARQ-apdu",
	"AARQ-apdu",
	&asn_OP_SEQUENCE,
	asn_DEF_AARQ_apdu_tags_1,
	sizeof(asn_DEF_AARQ_apdu_tags_1)
		/sizeof(asn_DEF_AARQ_apdu_tags_1[0]) - 1, /* 1 */
	asn_DEF_AARQ_apdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_AARQ_apdu_tags_1)
		/sizeof(asn_DEF_AARQ_apdu_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AARQ_apdu_1,
	16,	/* Elements count */
	&asn_SPC_AARQ_apdu_specs_1	/* Additional specs */
};

