/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "ABRT-diagnostic.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ABRT_diagnostic_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ABRT_diagnostic_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ABRT_diagnostic_value2enum_1[] = {
	{ 1,	15,	"no-reason-given" },
	{ 2,	14,	"protocol-error" },
	{ 3,	44,	"authentication-mechanism-name-not-recognized" },
	{ 4,	38,	"authentication-mechanism-name-required" },
	{ 5,	22,	"authentication-failure" },
	{ 6,	23,	"authentication-required" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ABRT_diagnostic_enum2value_1[] = {
	4,	/* authentication-failure(5) */
	2,	/* authentication-mechanism-name-not-recognized(3) */
	3,	/* authentication-mechanism-name-required(4) */
	5,	/* authentication-required(6) */
	0,	/* no-reason-given(1) */
	1	/* protocol-error(2) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_ABRT_diagnostic_specs_1 = {
	asn_MAP_ABRT_diagnostic_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ABRT_diagnostic_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ABRT_diagnostic_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ABRT_diagnostic = {
	"ABRT-diagnostic",
	"ABRT-diagnostic",
	&asn_OP_NativeEnumerated,
	asn_DEF_ABRT_diagnostic_tags_1,
	sizeof(asn_DEF_ABRT_diagnostic_tags_1)
		/sizeof(asn_DEF_ABRT_diagnostic_tags_1[0]), /* 1 */
	asn_DEF_ABRT_diagnostic_tags_1,	/* Same as above */
	sizeof(asn_DEF_ABRT_diagnostic_tags_1)
		/sizeof(asn_DEF_ABRT_diagnostic_tags_1[0]), /* 1 */
	{ &asn_OER_type_ABRT_diagnostic_constr_1, &asn_PER_type_ABRT_diagnostic_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ABRT_diagnostic_specs_1	/* Additional specs */
};

