/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "AE-qualifier.h"

static asn_oer_constraints_t asn_OER_type_AE_qualifier_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AE_qualifier_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AE_qualifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AE_qualifier, choice.ae_qualifier_form2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_AE_qualifier_form2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ae-qualifier-form2"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AE_qualifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* ae-qualifier-form2 */
};
asn_CHOICE_specifics_t asn_SPC_AE_qualifier_specs_1 = {
	sizeof(struct AE_qualifier),
	offsetof(struct AE_qualifier, _asn_ctx),
	offsetof(struct AE_qualifier, present),
	sizeof(((struct AE_qualifier *)0)->present),
	asn_MAP_AE_qualifier_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AE_qualifier = {
	"AE-qualifier",
	"AE-qualifier",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AE_qualifier_constr_1, &asn_PER_type_AE_qualifier_constr_1, CHOICE_constraint },
	asn_MBR_AE_qualifier_1,
	1,	/* Elements count */
	&asn_SPC_AE_qualifier_specs_1	/* Additional specs */
};

