/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AE_qualifier_form2_H_
#define	_AE_qualifier_form2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AE-qualifier-form2 */
typedef long	 AE_qualifier_form2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AE_qualifier_form2;
asn_struct_free_f AE_qualifier_form2_free;
asn_struct_print_f AE_qualifier_form2_print;
asn_constr_check_f AE_qualifier_form2_constraint;
ber_type_decoder_f AE_qualifier_form2_decode_ber;
der_type_encoder_f AE_qualifier_form2_encode_der;
xer_type_decoder_f AE_qualifier_form2_decode_xer;
xer_type_encoder_f AE_qualifier_form2_encode_xer;
oer_type_decoder_f AE_qualifier_form2_decode_oer;
oer_type_encoder_f AE_qualifier_form2_encode_oer;
per_type_decoder_f AE_qualifier_form2_decode_uper;
per_type_encoder_f AE_qualifier_form2_encode_uper;
per_type_decoder_f AE_qualifier_form2_decode_aper;
per_type_encoder_f AE_qualifier_form2_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AE_qualifier_form2_H_ */
#include <asn_internal.h>
