/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 */

#ifndef	_AE_title_form2_H_
#define	_AE_title_form2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AE-title-form2 */
typedef OBJECT_IDENTIFIER_t	 AE_title_form2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AE_title_form2;
asn_struct_free_f AE_title_form2_free;
asn_struct_print_f AE_title_form2_print;
asn_constr_check_f AE_title_form2_constraint;
ber_type_decoder_f AE_title_form2_decode_ber;
der_type_encoder_f AE_title_form2_encode_der;
xer_type_decoder_f AE_title_form2_decode_xer;
xer_type_encoder_f AE_title_form2_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AE_title_form2_H_ */
#include <asn_internal.h>
