/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 */

#ifndef	_AE_title_H_
#define	_AE_title_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AE-title-form2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AE_title_PR {
	AE_title_PR_NOTHING,	/* No components present */
	AE_title_PR_ae_title_form2,
	/* Extensions may appear below */
	
} AE_title_PR;

/* AE-title */
typedef struct AE_title {
	AE_title_PR present;
	union AE_title_u {
		AE_title_form2_t	 ae_title_form2;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AE_title_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AE_title;

#ifdef __cplusplus
}
#endif

#endif	/* _AE_title_H_ */
#include <asn_internal.h>
