/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Application_context_name_list_H_
#define	_Application_context_name_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Application-context-name.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Application-context-name-list */
typedef struct Application_context_name_list {
	A_SEQUENCE_OF(Application_context_name_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Application_context_name_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Application_context_name_list;
extern asn_SET_OF_specifics_t asn_SPC_Application_context_name_list_specs_1;
extern asn_TYPE_member_t asn_MBR_Application_context_name_list_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Application_context_name_list_H_ */
#include <asn_internal.h>
