/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 */

#ifndef	_MECHANISM_NAME_H_
#define	_MECHANISM_NAME_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TYPE-IDENTIFIER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MECHANISM-NAME */
typedef TYPE_IDENTIFIER_t	 MECHANISM_NAME_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MECHANISM_NAME;
asn_struct_free_f MECHANISM_NAME_free;
asn_struct_print_f MECHANISM_NAME_print;
asn_constr_check_f MECHANISM_NAME_constraint;
ber_type_decoder_f MECHANISM_NAME_decode_ber;
der_type_encoder_f MECHANISM_NAME_encode_der;
xer_type_decoder_f MECHANISM_NAME_decode_xer;
xer_type_encoder_f MECHANISM_NAME_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MECHANISM_NAME_H_ */
#include <asn_internal.h>
