/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RLRE_apdu_H_
#define	_RLRE_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Release-response-reason.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Association_information;

/* RLRE-apdu */
typedef struct RLRE_apdu {
	Release_response_reason_t	*reason;	/* OPTIONAL */
	struct Association_information	*user_information;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLRE_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLRE_apdu;
extern asn_SEQUENCE_specifics_t asn_SPC_RLRE_apdu_specs_1;
extern asn_TYPE_member_t asn_MBR_RLRE_apdu_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Association-information.h"

#endif	/* _RLRE_apdu_H_ */
#include <asn_internal.h>
