/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AP_invocation_identifier_H_
#define	_AP_invocation_identifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AP-invocation-identifier */
typedef long	 AP_invocation_identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AP_invocation_identifier;
asn_struct_free_f AP_invocation_identifier_free;
asn_struct_print_f AP_invocation_identifier_print;
asn_constr_check_f AP_invocation_identifier_constraint;
ber_type_decoder_f AP_invocation_identifier_decode_ber;
der_type_encoder_f AP_invocation_identifier_encode_der;
xer_type_decoder_f AP_invocation_identifier_decode_xer;
xer_type_encoder_f AP_invocation_identifier_encode_xer;
oer_type_decoder_f AP_invocation_identifier_decode_oer;
oer_type_encoder_f AP_invocation_identifier_encode_oer;
per_type_decoder_f AP_invocation_identifier_decode_uper;
per_type_encoder_f AP_invocation_identifier_encode_uper;
per_type_decoder_f AP_invocation_identifier_decode_aper;
per_type_encoder_f AP_invocation_identifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AP_invocation_identifier_H_ */
#include <asn_internal.h>
