/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AP_title_H_
#define	_AP_title_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AP-title-form2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AP_title_PR {
	AP_title_PR_NOTHING,	/* No components present */
	AP_title_PR_ap_title_form2
	/* Extensions may appear below */
	
} AP_title_PR;

/* AP-title */
typedef struct AP_title {
	AP_title_PR present;
	union AP_title_u {
		AP_title_form2_t	 ap_title_form2;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AP_title_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AP_title;
extern asn_CHOICE_specifics_t asn_SPC_AP_title_specs_1;
extern asn_TYPE_member_t asn_MBR_AP_title_1[1];
extern asn_per_constraints_t asn_PER_type_AP_title_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AP_title_H_ */
#include <asn_internal.h>
