/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Association_information_H_
#define	_Association_information_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EXTERNAL;

/* Association-information */
typedef struct Association_information {
	A_SEQUENCE_OF(struct EXTERNAL) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Association_information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Association_information;
extern asn_SET_OF_specifics_t asn_SPC_Association_information_specs_1;
extern asn_TYPE_member_t asn_MBR_Association_information_1[1];
extern asn_per_constraints_t asn_PER_type_Association_information_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNAL.h"

#endif	/* _Association_information_H_ */
#include <asn_internal.h>
