/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Implementation_data_H_
#define	_Implementation_data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Implementation-data */
typedef GraphicString_t	 Implementation_data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Implementation_data;
asn_struct_free_f Implementation_data_free;
asn_struct_print_f Implementation_data_print;
asn_constr_check_f Implementation_data_constraint;
ber_type_decoder_f Implementation_data_decode_ber;
der_type_encoder_f Implementation_data_encode_der;
xer_type_decoder_f Implementation_data_decode_xer;
xer_type_encoder_f Implementation_data_encode_xer;
oer_type_decoder_f Implementation_data_decode_oer;
oer_type_encoder_f Implementation_data_encode_oer;
per_type_decoder_f Implementation_data_decode_uper;
per_type_encoder_f Implementation_data_encode_uper;
per_type_decoder_f Implementation_data_decode_aper;
per_type_encoder_f Implementation_data_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Implementation_data_H_ */
#include <asn_internal.h>
