/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Abort_reason_H_
#define	_Abort_reason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Abort_reason {
	Abort_reason_reason_not_specified	= 0,
	Abort_reason_unrecognized_ppdu	= 1,
	Abort_reason_unexpected_ppdu	= 2,
	Abort_reason_unexpected_session_service_primitive	= 3,
	Abort_reason_unrecognized_ppdu_parameter	= 4,
	Abort_reason_unexpected_ppdu_parameter	= 5,
	Abort_reason_invalid_ppdu_parameter_value	= 6
} e_Abort_reason;

/* Abort-reason */
typedef long	 Abort_reason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abort_reason;
asn_struct_free_f Abort_reason_free;
asn_struct_print_f Abort_reason_print;
asn_constr_check_f Abort_reason_constraint;
ber_type_decoder_f Abort_reason_decode_ber;
der_type_encoder_f Abort_reason_encode_der;
xer_type_decoder_f Abort_reason_decode_xer;
xer_type_encoder_f Abort_reason_encode_xer;
oer_type_decoder_f Abort_reason_decode_oer;
oer_type_encoder_f Abort_reason_encode_oer;
per_type_decoder_f Abort_reason_decode_uper;
per_type_encoder_f Abort_reason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Abort_reason_H_ */
#include <asn_internal.h>
