/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Abstract_syntax_name_H_
#define	_Abstract_syntax_name_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Abstract-syntax-name */
typedef OBJECT_IDENTIFIER_t	 Abstract_syntax_name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abstract_syntax_name;
asn_struct_free_f Abstract_syntax_name_free;
asn_struct_print_f Abstract_syntax_name_print;
asn_constr_check_f Abstract_syntax_name_constraint;
ber_type_decoder_f Abstract_syntax_name_decode_ber;
der_type_encoder_f Abstract_syntax_name_encode_der;
xer_type_decoder_f Abstract_syntax_name_decode_xer;
xer_type_encoder_f Abstract_syntax_name_encode_xer;
oer_type_decoder_f Abstract_syntax_name_decode_oer;
oer_type_encoder_f Abstract_syntax_name_encode_oer;
per_type_decoder_f Abstract_syntax_name_decode_uper;
per_type_encoder_f Abstract_syntax_name_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Abstract_syntax_name_H_ */
#include <asn_internal.h>
