/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CPC_type_H_
#define	_CPC_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include "User-data.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CPC-type */
typedef User_data_t	 CPC_type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CPC_type;
asn_struct_free_f CPC_type_free;
asn_struct_print_f CPC_type_print;
asn_constr_check_f CPC_type_constraint;
ber_type_decoder_f CPC_type_decode_ber;
der_type_encoder_f CPC_type_encode_der;
xer_type_decoder_f CPC_type_decode_xer;
xer_type_encoder_f CPC_type_encode_xer;
oer_type_decoder_f CPC_type_decode_oer;
oer_type_encoder_f CPC_type_encode_oer;
per_type_decoder_f CPC_type_decode_uper;
per_type_encoder_f CPC_type_encode_uper;
per_type_decoder_f CPC_type_decode_aper;
per_type_encoder_f CPC_type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CPC_type_H_ */
#include <asn_internal.h>
