/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Presentation_requirements_H_
#define	_Presentation_requirements_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Presentation_requirements {
	Presentation_requirements_context_management	= 0,
	Presentation_requirements_restoration	= 1
} e_Presentation_requirements;

/* Presentation-requirements */
typedef BIT_STRING_t	 Presentation_requirements_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Presentation_requirements;
asn_struct_free_f Presentation_requirements_free;
asn_struct_print_f Presentation_requirements_print;
asn_constr_check_f Presentation_requirements_constraint;
ber_type_decoder_f Presentation_requirements_decode_ber;
der_type_encoder_f Presentation_requirements_encode_der;
xer_type_decoder_f Presentation_requirements_decode_xer;
xer_type_encoder_f Presentation_requirements_encode_xer;
oer_type_decoder_f Presentation_requirements_decode_oer;
oer_type_encoder_f Presentation_requirements_encode_oer;
per_type_decoder_f Presentation_requirements_decode_uper;
per_type_encoder_f Presentation_requirements_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Presentation_requirements_H_ */
#include <asn_internal.h>
