/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Protocol_version_H_
#define	_Protocol_version_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Protocol_version {
	Protocol_version_version_1	= 0
} e_Protocol_version;

/* Protocol-version */
typedef BIT_STRING_t	 Protocol_version_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Protocol_version;
asn_struct_free_f Protocol_version_free;
asn_struct_print_f Protocol_version_print;
asn_constr_check_f Protocol_version_constraint;
ber_type_decoder_f Protocol_version_decode_ber;
der_type_encoder_f Protocol_version_encode_der;
xer_type_decoder_f Protocol_version_decode_xer;
xer_type_encoder_f Protocol_version_encode_xer;
oer_type_decoder_f Protocol_version_decode_oer;
oer_type_encoder_f Protocol_version_encode_oer;
per_type_decoder_f Protocol_version_decode_uper;
per_type_encoder_f Protocol_version_encode_uper;
per_type_decoder_f Protocol_version_decode_aper;
per_type_encoder_f Protocol_version_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Protocol_version_H_ */
#include <asn_internal.h>
