/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_User_session_requirements_H_
#define	_User_session_requirements_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum User_session_requirements {
	User_session_requirements_half_duplex	= 0,
	User_session_requirements_duplex	= 1,
	User_session_requirements_expedited_data	= 2,
	User_session_requirements_minor_synchronize	= 3,
	User_session_requirements_major_synchronize	= 4,
	User_session_requirements_resynchronize	= 5,
	User_session_requirements_activity_management	= 6,
	User_session_requirements_negotiated_release	= 7,
	User_session_requirements_capability_data	= 8,
	User_session_requirements_exceptions	= 9,
	User_session_requirements_typed_data	= 10,
	User_session_requirements_symmetric_synchronize	= 11,
	User_session_requirements_data_separation	= 12
} e_User_session_requirements;

/* User-session-requirements */
typedef BIT_STRING_t	 User_session_requirements_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_User_session_requirements;
asn_struct_free_f User_session_requirements_free;
asn_struct_print_f User_session_requirements_print;
asn_constr_check_f User_session_requirements_constraint;
ber_type_decoder_f User_session_requirements_decode_ber;
der_type_encoder_f User_session_requirements_encode_der;
xer_type_decoder_f User_session_requirements_decode_xer;
xer_type_encoder_f User_session_requirements_encode_xer;
oer_type_decoder_f User_session_requirements_decode_oer;
oer_type_encoder_f User_session_requirements_encode_oer;
per_type_decoder_f User_session_requirements_decode_uper;
per_type_encoder_f User_session_requirements_encode_uper;
per_type_decoder_f User_session_requirements_decode_aper;
per_type_encoder_f User_session_requirements_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _User_session_requirements_H_ */
#include <asn_internal.h>
