/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_User_data_H_
#define	_User_data_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Simply-encoded-data.h"
#include "Fully-encoded-data.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum User_data_PR {
	User_data_PR_NOTHING,	/* No components present */
	User_data_PR_simply_encoded_data,
	User_data_PR_fully_encoded_data
	/* Extensions may appear below */
	
} User_data_PR;

/* User-data */
typedef struct User_data {
	User_data_PR present;
	union User_data_u {
		Simply_encoded_data_t	 simply_encoded_data;
		Fully_encoded_data_t	 fully_encoded_data;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} User_data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_User_data;
extern asn_CHOICE_specifics_t asn_SPC_User_data_specs_1;
extern asn_TYPE_member_t asn_MBR_User_data_1[2];
extern asn_per_constraints_t asn_PER_type_User_data_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _User_data_H_ */
#include <asn_internal.h>
