/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Context_list_H_
#define	_Context_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Presentation-context-identifier.h"
#include "Abstract-syntax-name.h"
#include "Transfer-syntax-name.h"
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct Context_list__Member {
	Presentation_context_identifier_t	 presentation_context_identifier;
	Abstract_syntax_name_t	 abstract_syntax_name;
	struct Context_list__Member__transfer_syntax_name_list {
		A_SEQUENCE_OF(Transfer_syntax_name_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} transfer_syntax_name_list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Context_list__Member;

/* Context-list */
typedef struct Context_list {
	A_SEQUENCE_OF(Context_list__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Context_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Context_list;
extern asn_SET_OF_specifics_t asn_SPC_Context_list_specs_1;
extern asn_TYPE_member_t asn_MBR_Context_list_1[1];
extern asn_per_constraints_t asn_PER_type_Context_list_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Context_list_H_ */
#include <asn_internal.h>
