/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Event_identifier_H_
#define	_Event_identifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Event_identifier {
	Event_identifier_cp_PPDU	= 0,
	Event_identifier_cpa_PPDU	= 1,
	Event_identifier_cpr_PPDU	= 2,
	Event_identifier_aru_PPDU	= 3,
	Event_identifier_arp_PPDU	= 4,
	Event_identifier_ac_PPDU	= 5,
	Event_identifier_aca_PPDU	= 6,
	Event_identifier_td_PPDU	= 7,
	Event_identifier_ttd_PPDU	= 8,
	Event_identifier_te_PPDU	= 9,
	Event_identifier_tc_PPDU	= 10,
	Event_identifier_tcc_PPDU	= 11,
	Event_identifier_rs_PPDU	= 12,
	Event_identifier_rsa_PPDU	= 13,
	Event_identifier_s_release_indication	= 14,
	Event_identifier_s_release_confirm	= 15,
	Event_identifier_s_token_give_indication	= 16,
	Event_identifier_s_token_please_indication	= 17,
	Event_identifier_s_control_give_indication	= 18,
	Event_identifier_s_sync_minor_indication	= 19,
	Event_identifier_s_sync_minor_confirm	= 20,
	Event_identifier_s_sync_major_indication	= 21,
	Event_identifier_s_sync_major_confirm	= 22,
	Event_identifier_s_p_exception_report_indication	= 23,
	Event_identifier_s_u_exception_report_indication	= 24,
	Event_identifier_s_activity_start_indication	= 25,
	Event_identifier_s_activity_resume_indication	= 26,
	Event_identifier_s_activity_interrupt_indication	= 27,
	Event_identifier_s_activity_interrupt_confirm	= 28,
	Event_identifier_s_activity_discard_indication	= 29,
	Event_identifier_s_activity_discard_confirm	= 30,
	Event_identifier_s_activity_end_indication	= 31,
	Event_identifier_s_activity_end_confirm	= 32
} e_Event_identifier;

/* Event-identifier */
typedef long	 Event_identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Event_identifier;
asn_struct_free_f Event_identifier_free;
asn_struct_print_f Event_identifier_print;
asn_constr_check_f Event_identifier_constraint;
ber_type_decoder_f Event_identifier_decode_ber;
der_type_encoder_f Event_identifier_encode_der;
xer_type_decoder_f Event_identifier_decode_xer;
xer_type_encoder_f Event_identifier_encode_xer;
oer_type_decoder_f Event_identifier_decode_oer;
oer_type_encoder_f Event_identifier_encode_oer;
per_type_decoder_f Event_identifier_decode_uper;
per_type_encoder_f Event_identifier_encode_uper;
per_type_decoder_f Event_identifier_decode_aper;
per_type_encoder_f Event_identifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Event_identifier_H_ */
#include <asn_internal.h>
