/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823-PRESENTATION"
 * 	found in "ISO8823_NEW.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Mode_selector_H_
#define	_Mode_selector_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum Mode_selector_PR {
	Mode_selector_PR_mode_value,	/* Member mode_value is present */
} Mode_selector_PR;
typedef enum Mode_selector__mode_value {
	Mode_selector__mode_value_x410_1984_mode	= 0,
	Mode_selector__mode_value_normal_mode	= 1
} e_Mode_selector__mode_value;

/* Mode-selector */
typedef struct Mode_selector {
	long	 mode_value;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pMode_selector, Mode_selector_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Mode_selector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Mode_selector;
extern asn_SET_specifics_t asn_SPC_Mode_selector_specs_1;
extern asn_TYPE_member_t asn_MBR_Mode_selector_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Mode_selector_H_ */
#include <asn_internal.h>
