/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AlternateAccess.h"

static asn_oer_constraints_t asn_OER_type_accessSelection_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_accessSelection_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_Member_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_Member_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_indexRange_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection__indexRange, lowIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lowIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection__indexRange, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberOfElements"
		},
};
static const ber_tlv_tag_t asn_DEF_indexRange_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_indexRange_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowIndex */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* numberOfElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_indexRange_specs_7 = {
	sizeof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection__indexRange),
	offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection__indexRange, _asn_ctx),
	asn_MAP_indexRange_tag2el_7,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_indexRange_7 = {
	"indexRange",
	"indexRange",
	&asn_OP_SEQUENCE,
	asn_DEF_indexRange_tags_7,
	sizeof(asn_DEF_indexRange_tags_7)
		/sizeof(asn_DEF_indexRange_tags_7[0]) - 1, /* 1 */
	asn_DEF_indexRange_tags_7,	/* Same as above */
	sizeof(asn_DEF_indexRange_tags_7)
		/sizeof(asn_DEF_indexRange_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_indexRange_7,
	2,	/* Elements count */
	&asn_SPC_indexRange_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_accessSelection_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_indexRange_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allElements"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_accessSelection_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* allElements */
};
static asn_CHOICE_specifics_t asn_SPC_accessSelection_specs_4 = {
	sizeof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection),
	offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection, _asn_ctx),
	offsetof(struct AlternateAccess__Member__selectAlternateAccess__accessSelection, present),
	sizeof(((struct AlternateAccess__Member__selectAlternateAccess__accessSelection *)0)->present),
	asn_MAP_accessSelection_tag2el_4,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_accessSelection_4 = {
	"accessSelection",
	"accessSelection",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_accessSelection_constr_4, &asn_PER_type_accessSelection_constr_4, CHOICE_constraint },
	asn_MBR_accessSelection_4,
	4,	/* Elements count */
	&asn_SPC_accessSelection_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectAlternateAccess_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess, accessSelection),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_accessSelection_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"accessSelection"
		},
	{ ATF_POINTER, 0, offsetof(struct AlternateAccess__Member__selectAlternateAccess, alternateAccess),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlternateAccess,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alternateAccess"
		},
};
static const ber_tlv_tag_t asn_DEF_selectAlternateAccess_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_selectAlternateAccess_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* alternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* allElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_selectAlternateAccess_specs_3 = {
	sizeof(struct AlternateAccess__Member__selectAlternateAccess),
	offsetof(struct AlternateAccess__Member__selectAlternateAccess, _asn_ctx),
	asn_MAP_selectAlternateAccess_tag2el_3,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectAlternateAccess_3 = {
	"selectAlternateAccess",
	"selectAlternateAccess",
	&asn_OP_SEQUENCE,
	asn_DEF_selectAlternateAccess_tags_3,
	sizeof(asn_DEF_selectAlternateAccess_tags_3)
		/sizeof(asn_DEF_selectAlternateAccess_tags_3[0]) - 1, /* 1 */
	asn_DEF_selectAlternateAccess_tags_3,	/* Same as above */
	sizeof(asn_DEF_selectAlternateAccess_tags_3)
		/sizeof(asn_DEF_selectAlternateAccess_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_selectAlternateAccess_3,
	2,	/* Elements count */
	&asn_SPC_selectAlternateAccess_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_named_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member__named, componentName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"componentName"
		},
	{ ATF_POINTER, 0, offsetof(struct AlternateAccess__Member__named, accesst),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_AlternateAccessSelection,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"accesst"
		},
};
static const ber_tlv_tag_t asn_DEF_named_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_named_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* componentName */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* selectAlternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 } /* allElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_named_specs_16 = {
	sizeof(struct AlternateAccess__Member__named),
	offsetof(struct AlternateAccess__Member__named, _asn_ctx),
	asn_MAP_named_tag2el_16,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_named_16 = {
	"named",
	"named",
	&asn_OP_SEQUENCE,
	asn_DEF_named_tags_16,
	sizeof(asn_DEF_named_tags_16)
		/sizeof(asn_DEF_named_tags_16[0]) - 1, /* 1 */
	asn_DEF_named_tags_16,	/* Same as above */
	sizeof(asn_DEF_named_tags_16)
		/sizeof(asn_DEF_named_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_named_16,
	2,	/* Elements count */
	&asn_SPC_named_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.selectAlternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_selectAlternateAccess_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"selectAlternateAccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IndexRangeSeq,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allElements"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.named),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_named_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"named"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* selectAlternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* allElements */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* named */
};
static asn_CHOICE_specifics_t asn_SPC_Member_specs_2 = {
	sizeof(struct AlternateAccess__Member),
	offsetof(struct AlternateAccess__Member, _asn_ctx),
	offsetof(struct AlternateAccess__Member, present),
	sizeof(((struct AlternateAccess__Member *)0)->present),
	asn_MAP_Member_tag2el_2,
	6,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_2 = {
	"CHOICE",
	"CHOICE",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Member_constr_2, &asn_PER_type_Member_constr_2, CHOICE_constraint },
	asn_MBR_Member_2,
	6,	/* Elements count */
	&asn_SPC_Member_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AlternateAccess_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Member_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_AlternateAccess_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_AlternateAccess_specs_1 = {
	sizeof(struct AlternateAccess),
	offsetof(struct AlternateAccess, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_AlternateAccess = {
	"AlternateAccess",
	"AlternateAccess",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_AlternateAccess_tags_1,
	sizeof(asn_DEF_AlternateAccess_tags_1)
		/sizeof(asn_DEF_AlternateAccess_tags_1[0]), /* 1 */
	asn_DEF_AlternateAccess_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlternateAccess_tags_1)
		/sizeof(asn_DEF_AlternateAccess_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_AlternateAccess_1,
	1,	/* Single element */
	&asn_SPC_AlternateAccess_specs_1	/* Additional specs */
};

