/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ConfirmedServiceResponse.h"

static asn_oer_constraints_t asn_OER_type_ConfirmedServiceResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ConfirmedServiceResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ConfirmedServiceResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.getNameList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetNameListResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getNameList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.read),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReadResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"read"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.write),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WriteResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"write"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.getVariableAccessAttributes),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetVariableAccessAttributesResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getVariableAccessAttributes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.defineNamedVariableList),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DefineNamedVariableListResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defineNamedVariableList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.getNamedVariableListAttributes),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetNamedVariableListAttributesResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getNamedVariableListAttributes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmedServiceResponse, choice.deleteNamedVariableList),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeleteNamedVariableListResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deleteNamedVariableList"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ConfirmedServiceResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* getNameList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* read */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* write */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 }, /* getVariableAccessAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 4, 0, 0 }, /* defineNamedVariableList */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 5, 0, 0 }, /* getNamedVariableListAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 6, 0, 0 } /* deleteNamedVariableList */
};
asn_CHOICE_specifics_t asn_SPC_ConfirmedServiceResponse_specs_1 = {
	sizeof(struct ConfirmedServiceResponse),
	offsetof(struct ConfirmedServiceResponse, _asn_ctx),
	offsetof(struct ConfirmedServiceResponse, present),
	sizeof(((struct ConfirmedServiceResponse *)0)->present),
	asn_MAP_ConfirmedServiceResponse_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ConfirmedServiceResponse = {
	"ConfirmedServiceResponse",
	"ConfirmedServiceResponse",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ConfirmedServiceResponse_constr_1, &asn_PER_type_ConfirmedServiceResponse_constr_1, CHOICE_constraint },
	asn_MBR_ConfirmedServiceResponse_1,
	7,	/* Elements count */
	&asn_SPC_ConfirmedServiceResponse_specs_1	/* Additional specs */
};

