/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Data.h"

static asn_oer_constraints_t asn_OER_type_Data_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Data_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Data_1[] = {
	{ ATF_POINTER, 0, offsetof(struct Data, choice.array),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataSequence,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"array"
		},
	{ ATF_POINTER, 0, offsetof(struct Data, choice.structure),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataSequence,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"structure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.boolean_new),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"boolean-new"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.bit_string),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bit-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.floating_point),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FloatingPoint,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"floating-point"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.octet_string),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"octet-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.visible_string),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"visible-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.binary_time),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeOfDay,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"binary-time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.mms_string),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MMSString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mms-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.utc_time),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UtcTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utc-time"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* boolean-new */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* bit-string */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* floating-point */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* octet-string */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* visible-string */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* binary-time */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 10, 0, 0 }, /* mms-string */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 11, 0, 0 } /* utc-time */
};
asn_CHOICE_specifics_t asn_SPC_Data_specs_1 = {
	sizeof(struct Data),
	offsetof(struct Data, _asn_ctx),
	offsetof(struct Data, present),
	sizeof(((struct Data *)0)->present),
	asn_MAP_Data_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Data = {
	"Data",
	"Data",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Data_constr_1, &asn_PER_type_Data_constr_1, CHOICE_constraint },
	asn_MBR_Data_1,
	12,	/* Elements count */
	&asn_SPC_Data_specs_1	/* Additional specs */
};

