/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetNameListRequest.h"

static asn_oer_constraints_t asn_OER_type_objectScope_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_objectScope_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_objectScope_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameListRequest__objectScope, choice.vmdSpecific),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vmdSpecific"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameListRequest__objectScope, choice.domainSpecific),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"domainSpecific"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameListRequest__objectScope, choice.aaSpecific),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aaSpecific"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_objectScope_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vmdSpecific */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* domainSpecific */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* aaSpecific */
};
static asn_CHOICE_specifics_t asn_SPC_objectScope_specs_3 = {
	sizeof(struct GetNameListRequest__objectScope),
	offsetof(struct GetNameListRequest__objectScope, _asn_ctx),
	offsetof(struct GetNameListRequest__objectScope, present),
	sizeof(((struct GetNameListRequest__objectScope *)0)->present),
	asn_MAP_objectScope_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_objectScope_3 = {
	"objectScope",
	"objectScope",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_objectScope_constr_3, &asn_PER_type_objectScope_constr_3, CHOICE_constraint },
	asn_MBR_objectScope_3,
	3,	/* Elements count */
	&asn_SPC_objectScope_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_GetNameListRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameListRequest, objectClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectClass,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"objectClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameListRequest, objectScope),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_objectScope_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"objectScope"
		},
	{ ATF_POINTER, 1, offsetof(struct GetNameListRequest, continueAfter),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"continueAfter"
		},
};
static const int asn_MAP_GetNameListRequest_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_GetNameListRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetNameListRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* objectClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* objectScope */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* continueAfter */
};
asn_SEQUENCE_specifics_t asn_SPC_GetNameListRequest_specs_1 = {
	sizeof(struct GetNameListRequest),
	offsetof(struct GetNameListRequest, _asn_ctx),
	asn_MAP_GetNameListRequest_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GetNameListRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetNameListRequest = {
	"GetNameListRequest",
	"GetNameListRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_GetNameListRequest_tags_1,
	sizeof(asn_DEF_GetNameListRequest_tags_1)
		/sizeof(asn_DEF_GetNameListRequest_tags_1[0]), /* 1 */
	asn_DEF_GetNameListRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetNameListRequest_tags_1)
		/sizeof(asn_DEF_GetNameListRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GetNameListRequest_1,
	3,	/* Elements count */
	&asn_SPC_GetNameListRequest_specs_1	/* Additional specs */
};

