/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ReadRequest.h"

static int asn_DFL_2_cmp_0(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_2_set_0(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
asn_TYPE_member_t asn_MBR_ReadRequest_1[] = {
	{ ATF_NOFLAGS, 1, offsetof(struct ReadRequest, specificationWithResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		&asn_DFL_2_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_2_set_0,	/* Set DEFAULT 0 */
		"specificationWithResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReadRequest, variableAccessSpecification),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VariableAccessSpecification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"variableAccessSpecification"
		},
};
static const int asn_MAP_ReadRequest_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ReadRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReadRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* specificationWithResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* variableAccessSpecification */
};
asn_SEQUENCE_specifics_t asn_SPC_ReadRequest_specs_1 = {
	sizeof(struct ReadRequest),
	offsetof(struct ReadRequest, _asn_ctx),
	asn_MAP_ReadRequest_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ReadRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReadRequest = {
	"ReadRequest",
	"ReadRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_ReadRequest_tags_1,
	sizeof(asn_DEF_ReadRequest_tags_1)
		/sizeof(asn_DEF_ReadRequest_tags_1[0]), /* 1 */
	asn_DEF_ReadRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReadRequest_tags_1)
		/sizeof(asn_DEF_ReadRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ReadRequest_1,
	2,	/* Elements count */
	&asn_SPC_ReadRequest_specs_1	/* Additional specs */
};

