/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ReadResponse.h"

static asn_TYPE_member_t asn_MBR_listOfAccessResult_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_AccessResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfAccessResult_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfAccessResult_specs_3 = {
	sizeof(struct ReadResponse__listOfAccessResult),
	offsetof(struct ReadResponse__listOfAccessResult, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfAccessResult_3 = {
	"listOfAccessResult",
	"listOfAccessResult",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfAccessResult_tags_3,
	sizeof(asn_DEF_listOfAccessResult_tags_3)
		/sizeof(asn_DEF_listOfAccessResult_tags_3[0]) - 1, /* 1 */
	asn_DEF_listOfAccessResult_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfAccessResult_tags_3)
		/sizeof(asn_DEF_listOfAccessResult_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_listOfAccessResult_3,
	1,	/* Single element */
	&asn_SPC_listOfAccessResult_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ReadResponse_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ReadResponse, variableAccessSpecification),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VariableAccessSpecification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"variableAccessSpecification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReadResponse, listOfAccessResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfAccessResult_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfAccessResult"
		},
};
static const int asn_MAP_ReadResponse_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ReadResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReadResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* variableAccessSpecification */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* listOfAccessResult */
};
asn_SEQUENCE_specifics_t asn_SPC_ReadResponse_specs_1 = {
	sizeof(struct ReadResponse),
	offsetof(struct ReadResponse, _asn_ctx),
	asn_MAP_ReadResponse_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ReadResponse_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReadResponse = {
	"ReadResponse",
	"ReadResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_ReadResponse_tags_1,
	sizeof(asn_DEF_ReadResponse_tags_1)
		/sizeof(asn_DEF_ReadResponse_tags_1[0]), /* 1 */
	asn_DEF_ReadResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReadResponse_tags_1)
		/sizeof(asn_DEF_ReadResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ReadResponse_1,
	2,	/* Elements count */
	&asn_SPC_ReadResponse_specs_1	/* Additional specs */
};

