/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "TypeSpecification.h"

static asn_oer_constraints_t asn_OER_type_TypeSpecification_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TypeSpecification_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static int asn_DFL_3_cmp_0(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_3_set_0(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
static asn_TYPE_member_t asn_MBR_array_2[] = {
	{ ATF_NOFLAGS, 1, offsetof(struct TypeSpecification__array, packed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		&asn_DFL_3_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_3_set_0,	/* Set DEFAULT 0 */
		"packed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__array, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberOfElements"
		},
	{ ATF_POINTER, 0, offsetof(struct TypeSpecification__array, elementType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeSpecification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"elementType"
		},
};
static const int asn_MAP_array_oms_2[] = { 0 };
static const ber_tlv_tag_t asn_DEF_array_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_array_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* packed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfElements */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* elementType */
};
static asn_SEQUENCE_specifics_t asn_SPC_array_specs_2 = {
	sizeof(struct TypeSpecification__array),
	offsetof(struct TypeSpecification__array, _asn_ctx),
	asn_MAP_array_tag2el_2,
	3,	/* Count of tags in the map */
	asn_MAP_array_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_array_2 = {
	"array",
	"array",
	&asn_OP_SEQUENCE,
	asn_DEF_array_tags_2,
	sizeof(asn_DEF_array_tags_2)
		/sizeof(asn_DEF_array_tags_2[0]) - 1, /* 1 */
	asn_DEF_array_tags_2,	/* Same as above */
	sizeof(asn_DEF_array_tags_2)
		/sizeof(asn_DEF_array_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_array_2,
	3,	/* Elements count */
	&asn_SPC_array_specs_2	/* Additional specs */
};

static int asn_DFL_7_cmp_0(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_7_set_0(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
static asn_TYPE_member_t asn_MBR_components_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StructComponent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_components_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_components_specs_8 = {
	sizeof(struct TypeSpecification__structure__components),
	offsetof(struct TypeSpecification__structure__components, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_components_8 = {
	"components",
	"components",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_components_tags_8,
	sizeof(asn_DEF_components_tags_8)
		/sizeof(asn_DEF_components_tags_8[0]) - 1, /* 1 */
	asn_DEF_components_tags_8,	/* Same as above */
	sizeof(asn_DEF_components_tags_8)
		/sizeof(asn_DEF_components_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_components_8,
	1,	/* Single element */
	&asn_SPC_components_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_structure_6[] = {
	{ ATF_NOFLAGS, 1, offsetof(struct TypeSpecification__structure, packed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		&asn_DFL_7_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_7_set_0,	/* Set DEFAULT 0 */
		"packed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__structure, components),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_components_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"components"
		},
};
static const int asn_MAP_structure_oms_6[] = { 0 };
static const ber_tlv_tag_t asn_DEF_structure_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_structure_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* packed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* components */
};
static asn_SEQUENCE_specifics_t asn_SPC_structure_specs_6 = {
	sizeof(struct TypeSpecification__structure),
	offsetof(struct TypeSpecification__structure, _asn_ctx),
	asn_MAP_structure_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_structure_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_structure_6 = {
	"structure",
	"structure",
	&asn_OP_SEQUENCE,
	asn_DEF_structure_tags_6,
	sizeof(asn_DEF_structure_tags_6)
		/sizeof(asn_DEF_structure_tags_6[0]) - 1, /* 1 */
	asn_DEF_structure_tags_6,	/* Same as above */
	sizeof(asn_DEF_structure_tags_6)
		/sizeof(asn_DEF_structure_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_structure_6,
	2,	/* Elements count */
	&asn_SPC_structure_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_floating_point_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__floating_point, format_width),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"format-width"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__floating_point, exponent_width),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exponent-width"
		},
};
static const ber_tlv_tag_t asn_DEF_floating_point_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_floating_point_tag2el_14[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* format-width */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* exponent-width */
};
static asn_SEQUENCE_specifics_t asn_SPC_floating_point_specs_14 = {
	sizeof(struct TypeSpecification__floating_point),
	offsetof(struct TypeSpecification__floating_point, _asn_ctx),
	asn_MAP_floating_point_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_floating_point_14 = {
	"floating-point",
	"floating-point",
	&asn_OP_SEQUENCE,
	asn_DEF_floating_point_tags_14,
	sizeof(asn_DEF_floating_point_tags_14)
		/sizeof(asn_DEF_floating_point_tags_14[0]) - 1, /* 1 */
	asn_DEF_floating_point_tags_14,	/* Same as above */
	sizeof(asn_DEF_floating_point_tags_14)
		/sizeof(asn_DEF_floating_point_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_floating_point_14,
	2,	/* Elements count */
	&asn_SPC_floating_point_specs_14	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TypeSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.array),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_array_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"array"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.structure),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_structure_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"structure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.boolean_new),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"boolean-new"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.bit_string),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bit-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.floating_point),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_floating_point_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"floating-point"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.octet_string),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"octet-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.visible_string),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"visible-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.binary_time),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"binary-time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.mms_string),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mms-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.utc_time),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utc-time"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TypeSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* boolean-new */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* bit-string */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* floating-point */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* octet-string */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* visible-string */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* binary-time */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 10, 0, 0 }, /* mms-string */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 11, 0, 0 } /* utc-time */
};
asn_CHOICE_specifics_t asn_SPC_TypeSpecification_specs_1 = {
	sizeof(struct TypeSpecification),
	offsetof(struct TypeSpecification, _asn_ctx),
	offsetof(struct TypeSpecification, present),
	sizeof(((struct TypeSpecification *)0)->present),
	asn_MAP_TypeSpecification_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TypeSpecification = {
	"TypeSpecification",
	"TypeSpecification",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TypeSpecification_constr_1, &asn_PER_type_TypeSpecification_constr_1, CHOICE_constraint },
	asn_MBR_TypeSpecification_1,
	12,	/* Elements count */
	&asn_SPC_TypeSpecification_specs_1	/* Additional specs */
};

