/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "VariableAccessSpecification.h"

static asn_oer_constraints_t asn_OER_type_VariableAccessSpecification_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_VariableAccessSpecification_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_listOfVariable_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VariableDef,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfVariable_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfVariable_specs_2 = {
	sizeof(struct VariableAccessSpecification__listOfVariable),
	offsetof(struct VariableAccessSpecification__listOfVariable, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfVariable_2 = {
	"listOfVariable",
	"listOfVariable",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfVariable_tags_2,
	sizeof(asn_DEF_listOfVariable_tags_2)
		/sizeof(asn_DEF_listOfVariable_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfVariable_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfVariable_tags_2)
		/sizeof(asn_DEF_listOfVariable_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_listOfVariable_2,
	1,	/* Single element */
	&asn_SPC_listOfVariable_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_VariableAccessSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification, choice.listOfVariable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_listOfVariable_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfVariable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VariableAccessSpecification, choice.variableListName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"variableListName"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_VariableAccessSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfVariable */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* variableListName */
};
asn_CHOICE_specifics_t asn_SPC_VariableAccessSpecification_specs_1 = {
	sizeof(struct VariableAccessSpecification),
	offsetof(struct VariableAccessSpecification, _asn_ctx),
	offsetof(struct VariableAccessSpecification, present),
	sizeof(((struct VariableAccessSpecification *)0)->present),
	asn_MAP_VariableAccessSpecification_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_VariableAccessSpecification = {
	"VariableAccessSpecification",
	"VariableAccessSpecification",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_VariableAccessSpecification_constr_1, &asn_PER_type_VariableAccessSpecification_constr_1, CHOICE_constraint },
	asn_MBR_VariableAccessSpecification_1,
	2,	/* Elements count */
	&asn_SPC_VariableAccessSpecification_specs_1	/* Additional specs */
};

