/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "VariableDef.h"

asn_TYPE_member_t asn_MBR_VariableDef_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VariableDef, variableSpecification),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_VariableSpecification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"variableSpecification"
		},
	{ ATF_POINTER, 1, offsetof(struct VariableDef, alternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlternateAccess,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alternateAccess"
		},
};
static const int asn_MAP_VariableDef_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_VariableDef_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VariableDef_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 } /* alternateAccess */
};
asn_SEQUENCE_specifics_t asn_SPC_VariableDef_specs_1 = {
	sizeof(struct VariableDef),
	offsetof(struct VariableDef, _asn_ctx),
	asn_MAP_VariableDef_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_VariableDef_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VariableDef = {
	"VariableDef",
	"VariableDef",
	&asn_OP_SEQUENCE,
	asn_DEF_VariableDef_tags_1,
	sizeof(asn_DEF_VariableDef_tags_1)
		/sizeof(asn_DEF_VariableDef_tags_1[0]), /* 1 */
	asn_DEF_VariableDef_tags_1,	/* Same as above */
	sizeof(asn_DEF_VariableDef_tags_1)
		/sizeof(asn_DEF_VariableDef_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_VariableDef_1,
	2,	/* Elements count */
	&asn_SPC_VariableDef_specs_1	/* Additional specs */
};

