/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "AE-title.h"

static asn_oer_constraints_t asn_OER_type_AE_title_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_AE_title_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_AE_title_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AE_title, choice.ae_title_form2),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_AE_title_form2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ae-title-form2"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AE_title_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* ae-title-form2 */
};
static asn_CHOICE_specifics_t asn_SPC_AE_title_specs_1 = {
	sizeof(struct AE_title),
	offsetof(struct AE_title, _asn_ctx),
	offsetof(struct AE_title, present),
	sizeof(((struct AE_title *)0)->present),
	asn_MAP_AE_title_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AE_title = {
	"AE-title",
	"AE-title",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AE_title_constr_1, &asn_PER_type_AE_title_constr_1, CHOICE_constraint },
	asn_MBR_AE_title_1,
	1,	/* Elements count */
	&asn_SPC_AE_title_specs_1	/* Additional specs */
};

