/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 */

#include "AE-title.h"

static asn_TYPE_member_t asn_MBR_AE_title_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AE_title, choice.ae_title_form2),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_AE_title_form2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ae-title-form2"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AE_title_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* ae-title-form2 */
};
static asn_CHOICE_specifics_t asn_SPC_AE_title_specs_1 = {
	sizeof(struct AE_title),
	offsetof(struct AE_title, _asn_ctx),
	offsetof(struct AE_title, present),
	sizeof(((struct AE_title *)0)->present),
	asn_MAP_AE_title_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AE_title = {
	"AE-title",
	"AE-title",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_AE_title_1,
	1,	/* Elements count */
	&asn_SPC_AE_title_specs_1	/* Additional specs */
};

