/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 */

#include "Authentication-value.h"

static int
memb_other_mechanism_name_constraint_5(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_other_mechanism_value_constraint_5(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static asn_TYPE_member_t asn_MBR_other_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct other, other_mechanism_name),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		memb_other_mechanism_name_constraint_5,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other-mechanism-name"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct other, other_mechanism_value),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		memb_other_mechanism_value_constraint_5,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other-mechanism-value"
		},
};
static const ber_tlv_tag_t asn_DEF_other_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_other_tag2el_5[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* other-mechanism-name */
};
static asn_SEQUENCE_specifics_t asn_SPC_other_specs_5 = {
	sizeof(struct other),
	offsetof(struct other, _asn_ctx),
	asn_MAP_other_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_other_5 = {
	"other",
	"other",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_other_tags_5,
	sizeof(asn_DEF_other_tags_5)
		/sizeof(asn_DEF_other_tags_5[0]) - 1, /* 1 */
	asn_DEF_other_tags_5,	/* Same as above */
	sizeof(asn_DEF_other_tags_5)
		/sizeof(asn_DEF_other_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_other_5,
	2,	/* Elements count */
	&asn_SPC_other_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Authentication_value_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.charstring),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GraphicString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"charstring"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.bitstring),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitstring"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.external),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EXTERNAL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"external"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.other),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_other_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Authentication_value_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* charstring */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* bitstring */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* external */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* other */
};
static asn_CHOICE_specifics_t asn_SPC_Authentication_value_specs_1 = {
	sizeof(struct Authentication_value),
	offsetof(struct Authentication_value, _asn_ctx),
	offsetof(struct Authentication_value, present),
	sizeof(((struct Authentication_value *)0)->present),
	asn_MAP_Authentication_value_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Authentication_value = {
	"Authentication-value",
	"Authentication-value",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Authentication_value_1,
	4,	/* Elements count */
	&asn_SPC_Authentication_value_specs_1	/* Additional specs */
};

