/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE-1"
 * 	found in "ACSE.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "Authentication-value.h"

static asn_oer_constraints_t asn_OER_type_Authentication_value_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Authentication_value_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_other_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value__other, other_mechanism_name),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"other-mechanism-name"
		},
	{ ATF_ANY_TYPE | ATF_NOFLAGS, 0, offsetof(struct Authentication_value__other, other_mechanism_value),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"other-mechanism-value"
		},
};
static const ber_tlv_tag_t asn_DEF_other_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_other_tag2el_5[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* other-mechanism-name */
};
static asn_SEQUENCE_specifics_t asn_SPC_other_specs_5 = {
	sizeof(struct Authentication_value__other),
	offsetof(struct Authentication_value__other, _asn_ctx),
	asn_MAP_other_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_other_5 = {
	"other",
	"other",
	&asn_OP_SEQUENCE,
	asn_DEF_other_tags_5,
	sizeof(asn_DEF_other_tags_5)
		/sizeof(asn_DEF_other_tags_5[0]) - 1, /* 1 */
	asn_DEF_other_tags_5,	/* Same as above */
	sizeof(asn_DEF_other_tags_5)
		/sizeof(asn_DEF_other_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_other_5,
	2,	/* Elements count */
	&asn_SPC_other_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Authentication_value_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.charstring),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GraphicString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"charstring"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.bitstring),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bitstring"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.external),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"external"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value, choice.other),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_other_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"other"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Authentication_value_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* charstring */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* bitstring */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* external */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* other */
};
asn_CHOICE_specifics_t asn_SPC_Authentication_value_specs_1 = {
	sizeof(struct Authentication_value),
	offsetof(struct Authentication_value, _asn_ctx),
	offsetof(struct Authentication_value, present),
	sizeof(((struct Authentication_value *)0)->present),
	asn_MAP_Authentication_value_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Authentication_value = {
	"Authentication-value",
	"Authentication-value",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Authentication_value_constr_1, &asn_PER_type_Authentication_value_constr_1, CHOICE_constraint },
	asn_MBR_Authentication_value_1,
	4,	/* Elements count */
	&asn_SPC_Authentication_value_specs_1	/* Additional specs */
};

