/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DefineNamedVariableListResponse_H_
#define	_DefineNamedVariableListResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DefineNamedVariableListResponse */
typedef NULL_t	 DefineNamedVariableListResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedVariableListResponse;
asn_struct_free_f DefineNamedVariableListResponse_free;
asn_struct_print_f DefineNamedVariableListResponse_print;
asn_constr_check_f DefineNamedVariableListResponse_constraint;
ber_type_decoder_f DefineNamedVariableListResponse_decode_ber;
der_type_encoder_f DefineNamedVariableListResponse_encode_der;
xer_type_decoder_f DefineNamedVariableListResponse_decode_xer;
xer_type_encoder_f DefineNamedVariableListResponse_encode_xer;
oer_type_decoder_f DefineNamedVariableListResponse_decode_oer;
oer_type_encoder_f DefineNamedVariableListResponse_encode_oer;
per_type_decoder_f DefineNamedVariableListResponse_decode_uper;
per_type_encoder_f DefineNamedVariableListResponse_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DefineNamedVariableListResponse_H_ */
#include "asn_internal.h"
