/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DefineNamedVariableListRequest_H_
#define	_DefineNamedVariableListRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectName.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableDef;

/* DefineNamedVariableListRequest */
typedef struct DefineNamedVariableListRequest {
	ObjectName_t	 variableListName;
	struct DefineNamedVariableListRequest__listOfVariable {
		A_SEQUENCE_OF(struct VariableDef) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedVariableListRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedVariableListRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineNamedVariableListRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineNamedVariableListRequest_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableDef.h"

#endif	/* _DefineNamedVariableListRequest_H_ */
#include "asn_internal.h"
