/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_MmsPdu_H_
#define	_MmsPdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ConfirmedRequestPdu.h"
#include "ConfirmedResponsePdu.h"
#include "UnconfirmedPDU.h"
#include "InitiateRequestPdu.h"
#include "InitiateResponsePdu.h"
#include "InitiateErrorPdu.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MmsPdu_PR {
	MmsPdu_PR_NOTHING,	/* No components present */
	MmsPdu_PR_confirmedRequestPdu,
	MmsPdu_PR_confirmedResponsePdu,
	MmsPdu_PR_unconfirmedPDU,
	MmsPdu_PR_initiateRequestPdu,
	MmsPdu_PR_initiateResponsePdu,
	MmsPdu_PR_initiateErrorPdu
} MmsPdu_PR;

/* MmsPdu */
typedef struct MmsPdu {
	MmsPdu_PR present;
	union MmsPdu_u {
		ConfirmedRequestPdu_t	 confirmedRequestPdu;
		ConfirmedResponsePdu_t	 confirmedResponsePdu;
		UnconfirmedPDU_t	 unconfirmedPDU;
		InitiateRequestPdu_t	 initiateRequestPdu;
		InitiateResponsePdu_t	 initiateResponsePdu;
		InitiateErrorPdu_t	 initiateErrorPdu;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MmsPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MmsPdu;

#ifdef __cplusplus
}
#endif

#endif	/* _MmsPdu_H_ */
#include "asn_internal.h"
