/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ScatteredAccessDescription_H_
#define	_ScatteredAccessDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "Identifier.h"
#include "VariableSpecification.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternateAccess;

/* Forward definitions */
typedef struct ScatteredAccessDescription__Member {
	Identifier_t	*componentName	/* OPTIONAL */;
	VariableSpecification_t	 variableSpecification;
	struct AlternateAccess	*alternateAccess	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScatteredAccessDescription__Member;

/* ScatteredAccessDescription */
typedef struct ScatteredAccessDescription {
	A_SEQUENCE_OF(ScatteredAccessDescription__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScatteredAccessDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScatteredAccessDescription;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateAccess.h"

#endif	/* _ScatteredAccessDescription_H_ */
#include "asn_internal.h"
