/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Unsigned16_H_
#define	_Unsigned16_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Unsigned16 */
typedef long	 Unsigned16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Unsigned16;
asn_struct_free_f Unsigned16_free;
asn_struct_print_f Unsigned16_print;
asn_constr_check_f Unsigned16_constraint;
ber_type_decoder_f Unsigned16_decode_ber;
der_type_encoder_f Unsigned16_encode_der;
xer_type_decoder_f Unsigned16_decode_xer;
xer_type_encoder_f Unsigned16_encode_xer;
oer_type_decoder_f Unsigned16_decode_oer;
oer_type_encoder_f Unsigned16_encode_oer;
per_type_decoder_f Unsigned16_decode_uper;
per_type_encoder_f Unsigned16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Unsigned16_H_ */
#include "asn_internal.h"
