/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Unsigned32_H_
#define	_Unsigned32_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Unsigned32 */
typedef unsigned long	 Unsigned32_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Unsigned32_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Unsigned32;
extern const asn_INTEGER_specifics_t asn_SPC_Unsigned32_specs_1;
asn_struct_free_f Unsigned32_free;
asn_struct_print_f Unsigned32_print;
asn_constr_check_f Unsigned32_constraint;
ber_type_decoder_f Unsigned32_decode_ber;
der_type_encoder_f Unsigned32_encode_der;
xer_type_decoder_f Unsigned32_decode_xer;
xer_type_encoder_f Unsigned32_encode_xer;
oer_type_decoder_f Unsigned32_decode_oer;
oer_type_encoder_f Unsigned32_encode_oer;
per_type_decoder_f Unsigned32_decode_uper;
per_type_encoder_f Unsigned32_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Unsigned32_H_ */
#include "asn_internal.h"
