/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VariableDef_H_
#define	_VariableDef_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VariableSpecification.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternateAccess;

/* VariableDef */
typedef struct VariableDef {
	VariableSpecification_t	 variableSpecification;
	struct AlternateAccess	*alternateAccess	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VariableDef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VariableDef;
extern asn_SEQUENCE_specifics_t asn_SPC_VariableDef_specs_1;
extern asn_TYPE_member_t asn_MBR_VariableDef_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateAccess.h"

#endif	/* _VariableDef_H_ */
#include "asn_internal.h"
